### ISSUE TITLE
Facing issue in building local set up.

### ISSUE THREAD

**Issue by Shivi-GH** [mercedes-benz/DnA#177]
Hello Team,

I am from DT team working on building DNA application for truck. I am trying to do local set up following below URL :
**https://github.com/mercedes-benz/DnA/blob/main/docs/SETUP-DOCKER-COMPOSE.md**

Its failing with below error, due to which image is not building.
![image](https://user-images.githubusercontent.com/103562929/163126397-4f014d42-223e-4d52-9fe8-01e357ec6ce8.png)

Could you please help on the same.

Thanks,
Shivika

**Comment by kameshbrao** [comment]
Hi, we already have the fix for this issue in our dev branch, however we will patch it to our master in sometime.

Regards,
Kamesh Rao

**Comment by kameshbrao** [comment]
The fix is now patched. Please take the latest main branch code

**Comment by agnelpraveen** [comment]
Related to the issue reported in -
https://stackoverflow.com/questions/71791347/npm-package-cannot-be-used-as-a-jsx-component-type-errors/71797147
