### ISSUE TITLE
Provide an image tag for vault

### ISSUE THREAD

**Issue by koppor** [mercedes-benz/DnA#1836]
I follow https://github.com/mercedes-benz/DnA/blob/main/docs/Install.md

    docker-compose -f docker-compose-local-basic.yml up -d

leads to following output:

    Error response from daemon: manifest for vault:latest not found: manifest unknown: manifest unknown

It seems that vault does not provide a "latest" tag. Thus, I patched `docker-compose-local-basic.yml`:

```diff
-    image: vault
+    image: vault:1.13.3
```

That helped to move forward a bit.

**Comment by VardhanDeva** [comment]
Hi @kapoor , 

Yes , You were right . Vault image does not have tag with latest.  we will test and update our code.
