### ISSUE TITLE
LegacyConfig Error on branch main

### ISSUE THREAD

**Issue by koppor** [mercedes-benz/DnA#1837]
I try to follow https://github.com/mercedes-benz/DnA/blob/main/docs/Install.md and could move forward a bit (with https://github.com/mercedes-benz/DnA/issues/1836)

Now, I get

```
 => [app-frontend base 4/5] RUN yarn                                                                                                                     82.6s  => ERROR [app-frontend base 5/5] RUN yarn build:docker                                                                                                  70.1s ------
 > [app-frontend base 5/5] RUN yarn build:docker:
0.440 yarn run v1.22.18
...
69.96 LegacyConfig:
69.96   ERROR in /usr/src/packages/frontend/src/components/icons/fullScreenMode/FullScreenModeIcon.tsx
69.96     14:9  error  Unknown property 'tooltip-data' found  react/no-unknown-property
69.96
69.96   /usr/src/packages/frontend/src/components/mbc/addTeamMember/addTeamMemberModal/AddTeamMemberModal.tsx
69.96     187:19  error  Unknown property 'required-error' found  react/no-unknown-property
69.96     280:19  error  Unknown property 'required-error' found  react/no-unknown-property
...
69.96   ✖ 123 problems (123 errors, 0 warnings)
69.96
69.96   LegacyConfig compiled with 2 errors
70.07 error Command failed with exit code 1.
```

How can this be fixed?

Maybe, I should switch from branch `main` to `dev`?

**Comment by VardhanDeva** [comment]
Hi @koppor  , 

We are testing the docker-compose with latest code . We will let you know once it is done .

Thanks ,
Ashokvardhan Devalla.

**Comment by VardhanDeva** [comment]
Hi @koppor , 

We tested the latest code in dev-branch and added a new docker-compose only to run dna-frontend , dna-backend and dependency services . 

Pull the latest code from **Dev** and execute the below command . 

**docker-compose -f docker-compose-dna.yml up app-frontend**

Test it and Let me know if you face any issues .
