### ISSUE TITLE
DNA okta

### ISSUE THREAD

**Issue by apurva9808** [mercedes-benz/DnA#210]
i have created app integration to okta for frontend with pkse and backend without pkse and after doing so and after making changes in "docker-compose-local-basic.yml", the front-end is not loading.
<img width="941" alt="image" src="https://user-images.githubusercontent.com/63505099/164452355-24d59518-8ffe-4328-bbb9-330e05ade0b1.png">

**Comment by sathishkumar-p** [comment]
Hello @apurva9808 
Could please share the env configuration in docker-compose for both frontend and backend by removing secret values ?

**Comment by apurva9808** [comment]
i m sharing the env config
[dockerdna.txt](https://github.com/mercedes-benz/DnA/files/8570194/dockerdna.txt)

**Comment by sathishkumar-p** [comment]
Hi,

OKTA url format is wrong. It should be like 
PROJECTSMO_FRONTEND_OAUTH2_LOGOUT_URL=https://dev-72.okta.com/oauth2/v1/logout 
in your case it was 
PROJECTSMO_FRONTEND_OAUTH2_LOGOUT_URL=dev-72.okta.com/oauth2/v1/logout 
and i observed the redirect url is http://localhost:9090 but the frontend application is running on 8080. So, i have updated the port for frontend from 8080 to 9090.  Now the frontend will run on 9090 port.

[dockerdna.txt](https://github.com/mercedes-benz/DnA/files/8571563/dockerdna.txt)
