### ISSUE TITLE
Licensing issue/question

### ISSUE THREAD

**Issue by nordominus** [mercedes-benz/DnA#318]
Hi,

the project states to be licensed under MIT, which can be found in the root folder and also in some subfolder of this project

But the package "DATAIKU" contains the Daimler Inner Source License "ISL", which means it is not under MIT: https://github.com/mercedes-benz/DnA/blob/main/packages/dataiku/LICENSE.md. It is definetly not an Open Source License. This makes it impossible to use DnA under MIT imho?

Can you please check this licensing issue and fix it if possible? Many thanks in advance!

Andreas Seidl <andreas.seidl@mercedes-benz.com> on behalf of MBition GmbH

**Comment by josipskafar** [comment]
Hi Andreas, thanks for a feedback, this is copy mistake. Will be fixed ASAP.

**Comment by josipskafar** [comment]
revoved through PR https://github.com/mercedes-benz/DnA/pull/324
