### ISSUE TITLE
Git Rebase Policy

### ISSUE THREAD

**Issue by konsloiz** [mercedes-benz/DnA#524]
Hello amazing DnA team!

Recently, while working on another project, I came across the ```git rebase``` policy. I thought that maybe it can be useful to this project in order to keep the git history cleaner and more readable.

**TL;DR**  

*Rebasing is the process of moving or combining a sequence of commits to a new base commit. ```git rebase``` will revise the commits but keep a clean organised history.*

## Git Rebase
Git rebase piles all the changes into a single patch and integrates the patch into the target branch. In the process of transferring the work from one branch to another, unwanted parts are removed to maintain a linear project history. The command is handy in the cases when you need the recent updates of the master branch in your feature branch, but the history of the master branch must remain clean ([W3docs](https://levelup.gitconnected.com/merge-or-rebase-thats-the-problem-11d65944b7e)).

![Linear vs non-linear history](https://www.bitsnbites.eu/wp-content/uploads/2015/12/1-nonlinear-vs-linear.png)

The primary reason for rebasing is to maintain a [linear project history](https://www.bitsnbites.eu/a-tidy-linear-git-history/). For example, consider a situation where the main branch has progressed since you started working on a feature branch. You want to get the latest updates to the main branch in your feature branch, but you want to keep your branch's history clean so it appears as if you've been working off the latest main branch. This gives the later benefit of a clean merge of your feature branch back into the main branch.

You can find more infos here: [git rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

## Disadvantages

- Rebasing can be dangerous! Rewriting history of shared branches is prone to team work breakage. This can be mitigated by doing the rebase/squash on a copy of the feature branch, but rebase carries the implication that competence and carefulness must be employed.

- It's more work: Using rebase to keep your feature branch updated requires that you resolve similar conflicts again and again. Yes, you can reuse recorded resolutions (rerere) sometimes, but merges win here: Just solve the conflicts one time, and you're set.

More info here: [Git team workflows: merge or rebase?](https://www.atlassian.com/git/articles/git-team-workflows-merge-or-rebase)

### Workflow
If you start working on a new feature/ticket go to your local master branch first:
```bash
$ git checkout master
```

Next, update the master with the newest changes:

```bash
$ git fetch origin master / git fetch --all
$ git rebase origin master
```

Create a new branch:

```bash
$ git checkout -b <newbranch> master
```

After finishing the work on the new branch it is time to rebase:

Rebasing allows to alter commits before pushing them to them to the repository via interactive rebasing against a branch, in this case master:

```bash
$ git rebase -i master
```

Or if the branch is already rebased against master (or another branch) you can rebase against the current HEAD:

```bash
$ git rebase -i HEAD~n
```

with n as the number of commits that need to be squashed or modified.

You can integrate multiple commits into one:

```bash
pick  33d5b7a Message for commit with some substantial work done in it #1
fixup 9480b3d Commit message with just a typo fix                      #2
pick  5c67e61 Commit message with more relevant work in it             #3
```

This way the second commit will be integrated into the first one, thus no longer cluttering up the history with uninteresting information. There are more ways to squash commit messages, this one is probably the simplest.

Changing the commit message in interactive rebase works as follows:

```bash
reword  33d5b7a different message for commit with some substantial work 
```

After squashing commits that are already pushed to the repository you might have to use force push, this is because you change the hash value of the commit and need to overwrite the value that is already stored there.

After the new branch is rebased and the commits are cleaned up you can push as usual.

## Git rebase policy for Github.com

If you decide to continue with ```git rebase```, Github provides a handful guide to configure pull request merge options. You can find it [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-rebasing-for-pull-requests).

## For the end 

This is just a topic for discussion. I don't mean to interfere in the internal working way of the DnA team! Feel free to ask questions, or directly decline the idea if you think that it wouldn't fit into the project.

Keep up the great job!

**Comment by josipskafar** [comment]
Thanks Kostas for this suggestion that for for sure help us in the future :)
